name: Build Android APK

on:
  push:
    branches: [main]

jobs:
  build_android:
    name: Build Android APK
    runs_on: linux-medium
    steps:
      - name: Checkout
        uses: eas/checkout

      - name: Install dependencies
        uses: eas/install_node_modules

      - name: Build APK
        uses: eas/build
        with:
          platform: android
          profile: preview
