import csv
import json

# Paths
tesco_csv = 'scraper/tesco_all_items.csv'
lidl_csv = 'scraper/lidl_all_items.csv'
data_js = 'web/js/data.js'

stores = [
    { 'id': 'tesco', 'name': 'Tesco', 'color': '#EE1C25', 'emoji': '🔴' },
    { 'id': 'lidl', 'name': 'Lidl', 'color': '#0050AA', 'emoji': '🔵' },
]

items = []

# Tesco
try:
    with open(tesco_csv, newline='', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for i, row in enumerate(reader, 1):
            items.append({
                'id': i,
                'name': row.get('name', ''),
                'quantity': row.get('quantity', ''),
                'category': row.get('category', ''),
                'prices': { 'tesco': float(row.get('price', '0').replace('€','').strip() or 0) },
                'history': { 'tesco': [float(row.get('price', '0').replace('€','').strip() or 0)] }
            })
except Exception:
    pass

# Lidl
try:
    with open(lidl_csv, newline='', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for i, row in enumerate(reader, len(items)+1):
            items.append({
                'id': i,
                'name': row.get('name', ''),
                'quantity': row.get('quantity', ''),
                'category': row.get('category', ''),
                'prices': { 'lidl': float(row.get('price', '0').replace('€','').strip() or 0) },
                'history': { 'lidl': [float(row.get('price', '0').replace('€','').strip() or 0)] }
            })
except Exception:
    pass

with open(data_js, 'w', encoding='utf-8') as f:
    f.write('// Auto-generated by csv_to_js.py\n')
    f.write('const stores = ' + json.dumps(stores, ensure_ascii=False) + ';\n')
    f.write('let items = ' + json.dumps(items, ensure_ascii=False) + ';\n')
