#!/usr/bin/env python3
"""
update_prices.py — One-command price updater for BasketBuddy.

Usage:
    python3 update_prices.py                           # uses grocery_prices_updated.csv
    python3 update_prices.py my_new_prices.csv         # uses a custom CSV file

What it does:
  1. Reads the CSV (same format as grocery_prices_updated.csv)
  2. Generates item data with separate quantity field
  3. Writes js/data.js directly (replaces all items)
  4. Bumps the cache version in index.html so the browser picks up changes

After running, just refresh http://localhost:8080 (Cmd+Shift+R to hard refresh).
"""

import csv, sys, os, re

# ── Config ─────────────────────────────────────────────────────────
CSV_FILE   = sys.argv[1] if len(sys.argv) > 1 else "grocery_prices_updated.csv"
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(SCRIPT_DIR)
DATA_JS    = os.path.join(PROJECT_ROOT, "web", "js", "data.js")
INDEX_HTML = os.path.join(PROJECT_ROOT, "web", "index.html")
MOBILE_DATA = os.path.join(PROJECT_ROOT, "mobile", "shared", "data.json")

# ── Parse CSV ──────────────────────────────────────────────────────
def parse_price(val):
    if val is None: return None
    val = val.strip()
    if not val or val == '0': return None
    try:
        p = float(val)
        return p if p > 0 else None
    except ValueError:
        return None

if not os.path.exists(CSV_FILE):
    print(f"❌ CSV file not found: {CSV_FILE}")
    sys.exit(1)

REQUIRED_COLUMNS = {'Itemtom', 'Category', 'Quantity / Weight',
                    'Asian Supermarket (€)', 'Lidl (€)', 'Super Value', 'Tesco (€)'}

rows = []
with open(CSV_FILE, newline='', encoding='utf-8-sig') as f:
    reader = csv.DictReader(f)
    missing = REQUIRED_COLUMNS - set(reader.fieldnames or [])
    if missing:
        print(f"❌ CSV is missing columns: {missing}")
        print(f"   Found columns: {list(reader.fieldnames or [])}")
        sys.exit(1)
    for r in reader:
        rows.append(dict(r))

items = []
item_id = 1

for r in rows:
    name = r.get('Itemtom', '').strip()
    if not name:
        continue
    qty = (r.get('Quantity / Weight') or '').strip()
    cat = (r.get('Category') or '').strip()

    prices = {}
    asian = parse_price(r.get('Asian Supermarket (€)'))
    lidl  = parse_price(r.get('Lidl (€)'))
    sv    = parse_price(r.get('Super Value'))
    tesco = parse_price(r.get('Tesco (€)'))

    if asian: prices['asian'] = asian
    if lidl:  prices['lidl'] = lidl
    if sv:    prices['supervalue'] = sv
    if tesco: prices['tesco'] = tesco

    if not prices:
        continue

    # Seed history with the current price only.
    # Real history accumulates as unified_scraper.py runs over time.
    history = {sid: [p] for sid, p in prices.items()}

    qty_display = qty if qty and qty != '-' else ''

    items.append({
        'id': item_id,
        'name': name,
        'quantity': qty_display,
        'category': cat if cat else 'Other',
        'prices': prices,
        'history': history
    })
    item_id += 1

print(f"✅ Parsed {len(items)} items from {CSV_FILE}")

# ── Generate data.js ──────────────────────────────────────────────
def fmt_item(it):
    p_str = ', '.join(f"{k}: {v}" for k, v in it['prices'].items())
    h_parts = [f"{k}: [{','.join(str(x) for x in v)}]" for k, v in it['history'].items()]
    h_str = ', '.join(h_parts)
    n = it['name'].replace("'", "\\'")
    q = it['quantity'].replace("'", "\\'")
    return (
        f"  {{\n"
        f"    id: {it['id']}, name: '{n}', quantity: '{q}', category: '{it['category']}',\n"
        f"    prices:  {{ {p_str} }},\n"
        f"    history: {{ {h_str} }}\n"
        f"  }}"
    )

js_items = ',\n'.join(fmt_item(it) for it in items)
next_id = len(items) + 1

data_js = f"""// ─── js/data.js ──────────────────────────────────────────────────
// Central data store. Auto-generated by update_prices.py — do not hand-edit.

const stores = [
  {{ id: 'tesco',      name: 'Tesco',              color: '#EE1C25', emoji: '🔴' }},
  {{ id: 'lidl',       name: 'Lidl',               color: '#0050AA', emoji: '🔵' }},
  {{ id: 'aldi',       name: 'Aldi',               color: '#FF6600', emoji: '🟠' }},
  {{ id: 'asian',      name: 'Asian Supermarket',   color: '#9B5DE5', emoji: '🟣' }},
  {{ id: 'supervalue', name: 'Super Value',         color: '#06D6A0', emoji: '🟢' }},
];

let items = [
{js_items},
];

let basket = [];
let splitItems = [];
let customStoreCount = 0;
let nextId = {next_id};
"""

with open(DATA_JS, 'w') as f:
    f.write(data_js)
print(f"✅ Wrote {len(items)} items to {DATA_JS}  (nextId = {next_id})")

# ── Bump cache version in index.html ──────────────────────────────
if os.path.exists(INDEX_HTML):
    html = open(INDEX_HTML, 'r').read()
    # Find current version number (e.g. ?v=3) and increment it
    match = re.search(r'\?v=(\d+)', html)
    if match:
        old_v = int(match.group(1))
        new_v = old_v + 1
        html = html.replace(f'?v={old_v}', f'?v={new_v}')
        with open(INDEX_HTML, 'w') as f:
            f.write(html)
        print(f"✅ Cache version bumped: v={old_v} → v={new_v} in index.html")
    else:
        print("⚠️  No ?v= found in index.html — skipping cache bump")
else:
    print("⚠️  index.html not found — skipping cache bump")

# ── Export JSON for mobile app ────────────────────────────────────
import json
mobile_dir = os.path.dirname(MOBILE_DATA)
if os.path.isdir(os.path.dirname(mobile_dir)):
    os.makedirs(mobile_dir, exist_ok=True)
    json_data = {
        "stores": [
            {"id": "tesco", "name": "Tesco", "color": "#EE1C25", "emoji": "🔴"},
            {"id": "lidl", "name": "Lidl", "color": "#0050AA", "emoji": "🔵"},
            {"id": "aldi", "name": "Aldi", "color": "#FF6600", "emoji": "🟠"},
            {"id": "asian", "name": "Asian Supermarket", "color": "#9B5DE5", "emoji": "🟣"},
            {"id": "supervalue", "name": "Super Value", "color": "#06D6A0", "emoji": "🟢"},
        ],
        "items": items,
    }
    with open(MOBILE_DATA, 'w') as f:
        json.dump(json_data, f, indent=2)
    print(f"✅ Wrote mobile data to {MOBILE_DATA}")

print(f"\n🎉 Done! Hard-refresh your browser (Cmd+Shift+R) to see updated prices.")
